### ISSUE TITLE
Update `uuid` package

### ISSUE THREAD

**Issue by ayuhito** [jetpack-io/typeid-go#3]
https://github.com/jetpack-io/typeid-go/blob/341e2b135e0609db272e6400f2f551487725824a/go.mod#L6 

The import for the `uuid` package has since changed to [`github.com/gofrs/uuid/v5`](https://pkg.go.dev/github.com/gofrs/uuid/v5) for a properly implemented version using `go.mod`.

I don't think there are any changes except for [this PR](https://github.com/gofrs/uuid/pull/116) introducing the change in import since then, but newer updates for the package should then go to this branch.

**Comment by loreto** [comment]
Good call out. Done!
